server:
  port: 8081


mybatis-plus:
  configuration:
    #mybatis-plus配置日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


spring:
  datasource:
    url: jdbc:mysql://139.159.232.210:3310/wiki?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: ctfliarlsx
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER  # 解决springboot2.6之后和swagger不兼容的问题






